Fix nixpacks Node.js package name
Error: undefined variable 'nodejs-20_x'
Fix: Changed to 'nodejs_20' (correct Nix package name)

Nix Package Names:
- Wrong: nodejs-20_x (underscore in wrong place)
- Correct: nodejs_20 (underscore after nodejs)

Result:
- Railway build will succeed
- Node 20 will be installed correctly